### ISSUE TITLE
Unable to install in Windows

### ISSUE THREAD

**Issue by lordgrenville** [apas/athena#10]
I managed to install (not without difficulty) on my Macbook, and it works really nicely. Thanks a lot! I had hoped to set it up on my Windows machine as well, but I've just gone through several hours of trying (including what you might expect - Python with and without conda, fresh install of Python3, editing my PATH several times, compiling some of the dependencies from source in Haskell). All to no avail. Python 3.4, 3.6, and 3.7 all give the same error. Stack trace:
```
==> Creating the virtual environment. . .
The path python3 (from --python=python3) does not exist
Traceback (most recent call last):
  File "install.py", line 49, in <module>
    raise e
  File "install.py", line 47, in <module>
    proc.check_call(["virtualenv", "--python=python3", "env"])
  File "C:\ProgramData\Miniconda3\envs\athena\lib\subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['virtualenv', '--python=python3', 'env']' returned non-zero exit status 3.
```

I can tell it has something to do with `subprocess`, but beyond that I've no idea. Any help would be appreciated!

**Comment by lordgrenville** [comment]
Fixed - going to make this a PR
